name: CI/CD Pipeline with SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-analyze:
    name: Build and Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures a full clone for accurate analysis

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'  # Other options: zulu, adopt, etc.

      # Step 3: Cache SonarCloud packages
      - name: Cache SonarCloud Packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Step 4: Cache Maven dependencies
      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 5: Start Dependency-Track Docker Container
      - name: Start Dependency-Track
        run: |
          docker run -d --name dependency-track \
            -p 8081:8081 \
            dependencytrack/bundle:latest

      # Step 6: Wait for Dependency-Track to Be Ready
      - name: Wait for Dependency-Track to Be Ready
        run: |
          for i in {1..20}; do
            curl -s -o /dev/null -w "%{http_code}" http://localhost:8081 || sleep 5;
          done

      # Step 7: Generate CycloneDX SBOM
      - name: Generate CycloneDX SBOM
        run: |
          mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom

      # Step 8: Upload SBOM to Dependency-Track
      - name: Upload SBOM to Dependency-Track
        env:
          API_KEY: odt_ksLKa8QOYOaBW9qpay6Sv7qpgOfDp2xe  # Default Dependency-Track API key
        run: |
          curl -X POST \
            -H "X-Api-Key: $API_KEY" \
            -F "projectName=YourProject" \
            -F "autoCreate=true" \
            -F "bom=@target/bom.xml" \
            http://localhost:8081/api/v1/bom

      # Step 9: Build and Analyze with SonarCloud
      - name: Build and Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required for PR decoration
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=ayush1452_userapi \
            -Dsonar.organization=ayush1452 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
          
      # Step 10: Stop Dependency-Track
      - name: Stop Dependency-Track
        run: |
          docker stop dependency-track
          docker rm dependency-track